### ISSUE TITLE
Death of the library

### ISSUE THREAD

**Issue by magemax** [frrmack/googlesearch#7]
Hello dear developpers,

I'm still quite new in the world of git, so many of the questions I ask might be stupid. 

As you state in the readme, the library doesn't work anymore due to the deprecation of some API on google side. 

I'm sorry to take your time like that, but I would like to take this occasion to understand a bit better what happened here :  I couldn't find any reference to the Google API going down this last month.

I guess my question is two-fold : 
- what happened exactly : which API is not usable anymore?  (searching for Free Google API on google does yield me a lot of unrelevant results)
- Is there hope of developping a new version of this API that uses another path to get Google search results ?  Seeing your tone in the forum it does not seem so and I would like to understand better why : Doesn't Google still provide a way to access his search results via API ? Is Google Custom Search not able to provide the same service ? Is this a licencing issue?

3rd bonus question  - Is there another way that would have been more appropriate for me to ask this question on github ?  I didn't see any PM possibilities, or anything that would look like a forum besides this page.

i'm not sure I have a point here, I just would like to understand why you abandonned this project, and if I could hope to code one by myself if I wanted to keep using it.  Thanks for your attention and for the time you could

By the way, I used your library to search any term restricted to stackoverflow.com, and return me the lines between <code>  tags, in order to be able to quickly get their answers directly in my python console.

Thanks for your time

**Comment by frrmack** [comment]
Hi magemax,

`googlesearch` was using [this api](https://developers.google.com/custom-search/json-api/v1/using_rest), which used to allow requests to `https://www.googleapis.com/customsearch/v1` without an API key (think of the key as an account login). It returned search results for a given query. `googlesearch` was using this. They were limiting the rate of queries (to something like 30 queries per twenty minutes or so) coming from the same IP.

They have recently stopped this behavior, and now all queries need to qo through the regular [Custom Search API](https://cse.google.com/cse/) with an API key. It's pretty much the same API, they just need a login. And custom search is still free, but instead of limiting the use rate based on the IP that sends the requests, they need your API key.

For one API key, the rate of free use is 100 search queries per day. [Any additional requests cost $5 per 1000 queries, up to 10K per day](https://developers.google.com/custom-search/json-api/v1/overview). As you can see, `googlesearch`cannot use one API key to send each user's requests to the API, the limit would be reached quickly every day. It could of course be modified for the new format and ask each user to get an API key from google and use that. I do not have the time to implement that right now; I would be happy to merge a pull request if someone else would want to code and test it.

In any case, it will not be as user friendly as before, since it requires a user to sign up for Google's Custom Search Engine and obtain an API key (it's not that hard, but a big energy barrier for the uninitiated), and the free limit is very low for most applications.

I hope this answers your questions.
